import type {ConversionRates} from "./currency.ts";

export interface Currency {
  readonly code: string,
  readonly displayName: string,
}

export function ratesToCurrencies(rates: ConversionRates): Currency[] {
  return Object.keys(rates).map(rate => {
    return currencies.find(c => c.code === rate)
  }).filter(c => c !== undefined)
}

export const currencies: Currency[] = [
  { code: "AED", displayName: "United Arab Emirates Dirham" },
  { code: "AFN", displayName: "Afghan Afghani" },
  { code: "ALL", displayName: "Albanian Lek" },
  { code: "AMD", displayName: "Armenian Dram" },
  { code: "ANG", displayName: "Netherlands Antillean Guilder" },
  { code: "AOA", displayName: "Angolan Kwanza" },
  { code: "ARS", displayName: "Argentine Peso" },
  { code: "AUD", displayName: "Australian Dollar" },
  { code: "AWG", displayName: "Aruban Florin" },
  { code: "AZN", displayName: "Azerbaijani Manat" },
  { code: "BAM", displayName: "Bosnia-Herzegovina Convertible Mark" },
  { code: "BBD", displayName: "Barbadian Dollar" },
  { code: "BDT", displayName: "Bangladeshi Taka" },
  { code: "BGN", displayName: "Bulgarian Lev" },
  { code: "BHD", displayName: "Bahraini Dinar" },
  { code: "BIF", displayName: "Burundian Franc" },
  { code: "BMD", displayName: "Bermudan Dollar" },
  { code: "BND", displayName: "Brunei Dollar" },
  { code: "BOB", displayName: "Bolivian Boliviano" },
  { code: "BRL", displayName: "Brazilian Real" },
  { code: "BSD", displayName: "Bahamian Dollar" },
  { code: "BTC", displayName: "Bitcoin" },
  { code: "BTN", displayName: "Bhutanese Ngultrum" },
  { code: "BWP", displayName: "Botswanan Pula" },
  { code: "BYN", displayName: "Belarusian Ruble" },
  { code: "BZD", displayName: "Belize Dollar" },
  { code: "CAD", displayName: "Canadian Dollar" },
  { code: "CDF", displayName: "Congolese Franc" },
  { code: "CHF", displayName: "Swiss Franc" },
  { code: "CLF", displayName: "Chilean Unit of Account (UF)" },
  { code: "CLP", displayName: "Chilean Peso" },
  { code: "CNH", displayName: "Chinese Yuan (Offshore)" },
  { code: "CNY", displayName: "Chinese Yuan" },
  { code: "COP", displayName: "Colombian Peso" },
  { code: "CRC", displayName: "Costa Rican Colón" },
  { code: "CUC", displayName: "Cuban Convertible Peso" },
  { code: "CUP", displayName: "Cuban Peso" },
  { code: "CVE", displayName: "Cape Verdean Escudo" },
  { code: "CZK", displayName: "Czech Republic Koruna" },
  { code: "DJF", displayName: "Djiboutian Franc" },
  { code: "DKK", displayName: "Danish Krone" },
  { code: "DOP", displayName: "Dominican Peso" },
  { code: "DZD", displayName: "Algerian Dinar" },
  { code: "EGP", displayName: "Egyptian Pound" },
  { code: "ERN", displayName: "Eritrean Nakfa" },
  { code: "ETB", displayName: "Ethiopian Birr" },
  { code: "EUR", displayName: "Euro" },
  { code: "FJD", displayName: "Fijian Dollar" },
  { code: "FKP", displayName: "Falkland Islands Pound" },
  { code: "GBP", displayName: "British Pound Sterling" },
  { code: "GEL", displayName: "Georgian Lari" },
  { code: "GGP", displayName: "Guernsey Pound" },
  { code: "GHS", displayName: "Ghanaian Cedi" },
  { code: "GIP", displayName: "Gibraltar Pound" },
  { code: "GMD", displayName: "Gambian Dalasi" },
  { code: "GNF", displayName: "Guinean Franc" },
  { code: "GTQ", displayName: "Guatemalan Quetzal" },
  { code: "GYD", displayName: "Guyanaese Dollar" },
  { code: "HKD", displayName: "Hong Kong Dollar" },
  { code: "HNL", displayName: "Honduran Lempira" },
  { code: "HRK", displayName: "Croatian Kuna" },
  { code: "HTG", displayName: "Haitian Gourde" },
  { code: "HUF", displayName: "Hungarian Forint" },
  { code: "IDR", displayName: "Indonesian Rupiah" },
  { code: "ILS", displayName: "Israeli New Sheqel" },
  { code: "IMP", displayName: "Manx pound" },
  { code: "INR", displayName: "Indian Rupee" },
  { code: "IQD", displayName: "Iraqi Dinar" },
  { code: "IRR", displayName: "Iranian Rial" },
  { code: "ISK", displayName: "Icelandic Króna" },
  { code: "JEP", displayName: "Jersey Pound" },
  { code: "JMD", displayName: "Jamaican Dollar" },
  { code: "JOD", displayName: "Jordanian Dinar" },
  { code: "JPY", displayName: "Japanese Yen" },
  { code: "KES", displayName: "Kenyan Shilling" },
  { code: "KGS", displayName: "Kyrgystani Som" },
  { code: "KHR", displayName: "Cambodian Riel" },
  { code: "KMF", displayName: "Comorian Franc" },
  { code: "KPW", displayName: "North Korean Won" },
  { code: "KRW", displayName: "South Korean Won" },
  { code: "KWD", displayName: "Kuwaiti Dinar" },
  { code: "KYD", displayName: "Cayman Islands Dollar" },
  { code: "KZT", displayName: "Kazakhstani Tenge" },
  { code: "LAK", displayName: "Laotian Kip" },
  { code: "LBP", displayName: "Lebanese Pound" },
  { code: "LKR", displayName: "Sri Lankan Rupee" },
  { code: "LRD", displayName: "Liberian Dollar" },
  { code: "LSL", displayName: "Lesotho Loti" },
  { code: "LYD", displayName: "Libyan Dinar" },
  { code: "MAD", displayName: "Moroccan Dirham" },
  { code: "MDL", displayName: "Moldovan Leu" },
  { code: "MGA", displayName: "Malagasy Ariary" },
  { code: "MKD", displayName: "Macedonian Denar" },
  { code: "MMK", displayName: "Myanma Kyat" },
  { code: "MNT", displayName: "Mongolian Tugrik" },
  { code: "MOP", displayName: "Macanese Pataca" },
  { code: "MRU", displayName: "Mauritanian Ouguiya" },
  { code: "MUR", displayName: "Mauritian Rupee" },
  { code: "MVR", displayName: "Maldivian Rufiyaa" },
  { code: "MWK", displayName: "Malawian Kwacha" },
  { code: "MXN", displayName: "Mexican Peso" },
  { code: "MYR", displayName: "Malaysian Ringgit" },
  { code: "MZN", displayName: "Mozambican Metical" },
  { code: "NAD", displayName: "Namibian Dollar" },
  { code: "NGN", displayName: "Nigerian Naira" },
  { code: "NIO", displayName: "Nicaraguan Córdoba" },
  { code: "NOK", displayName: "Norwegian Krone" },
  { code: "NPR", displayName: "Nepalese Rupee" },
  { code: "NZD", displayName: "New Zealand Dollar" },
  { code: "OMR", displayName: "Omani Rial" },
  { code: "PAB", displayName: "Panamanian Balboa" },
  { code: "PEN", displayName: "Peruvian Nuevo Sol" },
  { code: "PGK", displayName: "Papua New Guinean Kina" },
  { code: "PHP", displayName: "Philippine Peso" },
  { code: "PKR", displayName: "Pakistani Rupee" },
  { code: "PLN", displayName: "Polish Zloty" },
  { code: "PYG", displayName: "Paraguayan Guarani" },
  { code: "QAR", displayName: "Qatari Rial" },
  { code: "RON", displayName: "Romanian Leu" },
  { code: "RSD", displayName: "Serbian Dinar" },
  { code: "RUB", displayName: "Russian Ruble" },
  { code: "RWF", displayName: "Rwandan Franc" },
  { code: "SAR", displayName: "Saudi Riyal" },
  { code: "SBD", displayName: "Solomon Islands Dollar" },
  { code: "SCR", displayName: "Seychellois Rupee" },
  { code: "SDG", displayName: "Sudanese Pound" },
  { code: "SEK", displayName: "Swedish Krona" },
  { code: "SGD", displayName: "Singapore Dollar" },
  { code: "SHP", displayName: "Saint Helena Pound" },
  { code: "SLL", displayName: "Sierra Leonean Leone" },
  { code: "SOS", displayName: "Somali Shilling" },
  { code: "SRD", displayName: "Surinamese Dollar" },
  { code: "SSP", displayName: "South Sudanese Pound" },
  { code: "STD", displayName: "São Tomé and Príncipe Dobra (pre-2018)" },
  { code: "STN", displayName: "São Tomé and Príncipe Dobra" },
  { code: "SVC", displayName: "Salvadoran Colón" },
  { code: "SYP", displayName: "Syrian Pound" },
  { code: "SZL", displayName: "Swazi Lilangeni" },
  { code: "THB", displayName: "Thai Baht" },
  { code: "TJS", displayName: "Tajikistani Somoni" },
  { code: "TMT", displayName: "Turkmenistani Manat" },
  { code: "TND", displayName: "Tunisian Dinar" },
  { code: "TOP", displayName: "Tongan Pa'anga" },
  { code: "TRY", displayName: "Turkish Lira" },
  { code: "TTD", displayName: "Trinidad and Tobago Dollar" },
  { code: "TWD", displayName: "New Taiwan Dollar" },
  { code: "TZS", displayName: "Tanzanian Shilling" },
  { code: "UAH", displayName: "Ukrainian Hryvnia" },
  { code: "UGX", displayName: "Ugandan Shilling" },
  { code: "USD", displayName: "United States Dollar" },
  { code: "UYU", displayName: "Uruguayan Peso" },
  { code: "UZS", displayName: "Uzbekistan Som" },
  { code: "VEF", displayName: "Venezuelan Bolívar Fuerte (Old)" },
  { code: "VES", displayName: "Venezuelan Bolívar Soberano" },
  { code: "VND", displayName: "Vietnamese Dong" },
  { code: "VUV", displayName: "Vanuatu Vatu" },
  { code: "WST", displayName: "Samoan Tala" },
  { code: "XAF", displayName: "CFA Franc BEAC" },
  { code: "XAG", displayName: "Silver Ounce" },
  { code: "XAU", displayName: "Gold Ounce" },
  { code: "XCD", displayName: "East Caribbean Dollar" },
  { code: "XDR", displayName: "Special Drawing Rights" },
  { code: "XOF", displayName: "CFA Franc BCEAO" },
  { code: "XPD", displayName: "Palladium Ounce" },
  { code: "XPF", displayName: "CFP Franc" },
  { code: "XPT", displayName: "Platinum Ounce" },
  { code: "YER", displayName: "Yemeni Rial" },
  { code: "ZAR", displayName: "South African Rand" },
  { code: "ZMW", displayName: "Zambian Kwacha" },
  { code: "ZWL", displayName: "Zimbabwean Dollar" }
]
